cmd: npm test
targets:
  PreTest:
      cmd: "npm run pretest"
  TestSuite:
      cmd: "npm run test"
  ContinuesTest:
      cmd: "mocha -w tests/index.js"
  Build:
      cmd: "npm run dist"
  Documentation:
      cmd: "npm run doc"
  Publish:
      cmd: "npm test && npm run doc && git add -A && git commit -a -m 'Release Candidate' && npm run dist && npm publish"
